version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/node:12.10.0-buster
    steps:
      - checkout

      - run:
          name: 'Add required packages'
          command: |
            sudo apt update
            sudo apt install -y imagemagick inkscape librsvg2-bin
            convert -version
            inkscape --version
            rsvg-convert --version

      - run: mkdir -p release

      - run: inkscape -l release/cocoa.svg cocoa.svg

      - run: |
          for size in {64,128,192,256,384,512}; do
            rsvg-convert -f png -w $size -h $size -o release/cocoa-$size.png cocoa.svg
            convert release/cocoa-$size.png release/cocoa-$size.jpg
          done

      - run: convert cocoa.svg -define icon:auto-resize=48,32,24,16 release/cocoa.ico

      - store_artifacts:
          path: release

      - persist_to_workspace:
          root: ~/work
          paths:
            - release

  deploy:
    working_directory: ~/work
    docker:
      - image: circleci/node:12.10.0-buster
    steps:
      - add_ssh_keys:
          fingerprints:
            - "36:76:d7:36:b0:c6:fc:46:f5:0b:47:3a:c3:97:b9:a9"

      - attach_workspace:
          at: ~/work

      - run:
          name: Add github.com to ~/.ssh/known_hosts
          command: |
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts

      - run:
          name: Set git user and email
          command: |
            git config --global user.name $GH_NAME
            git config --global user.email $GH_EMAIL

      - deploy:
          name: Deploy
          working_directory: ~/work/release
          command: |
            git init
            git checkout --orphan release
            git add -A
            git commit --allow-empty -m '(⋈◍＞◡＜◍)。✧♡ [skip ci]'
            git remote add origin $CIRCLE_REPOSITORY_URL
            git push -f origin release

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
