name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: 'Add required packages'
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick inkscape librsvg2-bin

      - run: convert -version
      - run: inkscape --version
      - run: rsvg-convert --version

      - run: mkdir -p release

      - run: inkscape -l release/cocoa.svg cocoa.svg

      - run: |
          for size in {64,128,192,256,384,512}; do
            rsvg-convert -f png -w $size -h $size -o release/cocoa-$size.png cocoa.svg
            convert release/cocoa-$size.png release/cocoa-$size.jpg
          done

      - run: convert cocoa.svg -define icon:auto-resize=48,32,24,16 release/cocoa.ico

      - uses: actions/upload-artifact@main
        with:
          name: release
          path: release

  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@main
        with:
          name: release

      - name: Deploy
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git switch --orphan release
          git add -A
          git commit --allow-empty -m "(⋈◍＞◡＜◍)。✧♡ "
          git push -f "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}" HEAD
