name: build
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: dd required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick inkscape librsvg2-bin

      - run: convert -version
      - run: inkscape --version
      - run: rsvg-convert --version

      - run: mkdir -p release

      - run: inkscape -l -o release/cocoa.svg cocoa.svg

      - run: |
          for size in {64,128,192,256,384,512}; do
            rsvg-convert -f png -w "$size" -h "$size" -o "release/cocoa-${size}.png" cocoa.svg
            convert "release/cocoa-${size}.png" "release/cocoa-${size}.jpg"
          done

      - run: convert cocoa.svg -define icon:auto-resize=48,32,24,16 release/cocoa.ico

      - uses: actions/upload-artifact@v4.6.1
        with:
          name: release
          path: release

  deploy:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: release
          path: new

      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          ref: release
          path: old

      - name: Deploy
        run: |
          if ! diff -r -q -x .git old new; then
            git -C old config user.name "GitHub Actions"
            git -C old config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git -C old switch --orphan "tmp-${{ github.run_id }}"
            cp -r new/* old/
            git -C old add -A
            git -C old commit --allow-empty -m "(⋈◍＞◡＜◍)。✧♡ "
            git -C old push --force origin HEAD:release
          fi
